- name: Configure web server and deploy wordpress
  hosts: wordpresshost
  become: True
  remote_user: "ubuntu"
  gather_facts: True
  roles:
    - common
    - php
    - database
    - web_server
    - ssl
    - wordpress
