- name: Create an EC2 instance
  ec2:
    keypair: "{{ keypair }}"
    region: "{{ aws_region }}"
    group_id: "{{ group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    count_tag:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    exact_count: "{{ instance_count }}"
  register: ec2

- name: Add new instances to host group
  add_host: hostname={{ item.public_dns_name }} groupname=launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"
